# Dockerfile for Consumer Service
FROM python:3.9

WORKDIR /app

COPY consumer/consumer.py .
COPY consumer/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "consumer.py"]
