# Dockerfile for Producer Service
FROM python:3.9

WORKDIR /app

COPY producer/producer.py .
COPY producer/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "producer.py"]
